name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-linux:
    name: Run tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: '19.3.1.java11'
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.469'
      - run: clojure -Sdescribe
      - run: lein test
