name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: '19.3.1.java11'
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.469'
      - run: clojure -Sdescribe
      - run: lein uberjar
      - uses: actions/upload-artifact@master
        name: Generating artifact
        with:
          name: clojure-twitter-api
          path: ./target/uberjar/twitter-api-0.1.0-SNAPSHOT-standalone.jar

  tests-linux:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: '19.3.1.java11'
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.469'
      - run: clojure -Sdescribe
      - run: lein test
